# Define the name of the workflow
name: Validate with hassfest

# Define the events that trigger the workflow
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

# Define the jobs that the workflow will perform
jobs:
  validate:
    # Define the environment the job will run on
    runs-on: "ubuntu-latest"
    # Define the individual steps that make up the job
    steps:
      # Set up Node.js 16.x before checking out the code repository
#      - name: Setup Node.js 16.x
#        uses: actions/setup-node@v3
#        with:
#          node-version: "16.x"
      # Check out the code repository that triggered the workflow
      - uses: actions/checkout@v3
      # Run hassfest on the configuration files
      - uses: home-assistant/actions/hassfest@master
