# Define the name of the workflow
name: Validate

# Define the events that trigger the workflow
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  # Allow the workflow to be triggered manually from the Actions tab
  workflow_dispatch:

# Define the jobs that the workflow will perform
jobs:
  # Define a job named 'validate-hacs'
  validate-hacs:
    # Define the environment the job will run on
    runs-on: "ubuntu-latest"
    # Define the individual steps that make up the job
    steps:
      # Check out the code repository that triggered the workflow
      - uses: "actions/checkout@v3"
      # Run HACS validation on the integration category
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
